name: EAS Build Android

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g eas-cli
      - run: npm ci

      - name: Login to Expo
        run: eas whoami || echo $EXPO_TOKEN | eas login --token
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android App
        run: eas build --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
